immutablePatterns:
  - .pnp.*

initScope: next-mobx-store

nodeLinker: pnp

packageExtensions:
  "@testing-library/react-hooks@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@testing-library/react@*":
    dependencies:
      react: "*"
      react-dom: "*"
  debug@*:
    dependencies:
      supports-color: 8.1.1
  eslint-config-custom@*:
    dependencies:
      eslint: "*"
      eslint-plugin-turbo: "*"
      prettier: "*"
  eslint-plugin-prettier@*:
    dependencies:
      eslint: "*"
      prettier: "*"
  eslint-plugin-turbo@*:
    dependencies:
      eslint: "*"
  next@*:
    dependencies:
      react: "*"
      react-dom: "*"
  ts-jest@*:
    dependencies:
      jest: "*"

pnpEnableEsmLoader: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.6.4.cjs
