nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.6.3.cjs

immutablePatterns:
  - .pnp.*

initScope: next-mobx-store

preferInteractive: true

pnpEnableEsmLoader: true

packageExtensions:
  eslint-plugin-turbo@*:
    dependencies:
      eslint: "*"
  eslint-config-custom@*:
    dependencies:
      eslint-plugin-turbo: "*"
      eslint: "*"
      prettier: "*"

  eslint-plugin-prettier@*:
    dependencies:
      eslint: "*"
      prettier: "*"

  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": "*"

  "@testing-library/react@*":
    dependencies:
      react-dom: "*"

  next@*:
    dependencies:
      react: "*"
      react-dom: "*"
