compressionLevel: 0

enableGlobalCache: false

enableTransparentWorkspaces: false

lockfileFilename: ./yarn.nm.lock

nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  "@testing-library/react@*":
    dependencies:
      react: "*"
      react-dom: "*"
  debug@*:
    dependencies:
      supports-color: 8.1.1
  eslint-config-custom@*:
    dependencies:
      eslint: "*"
      eslint-plugin-turbo: "*"
      prettier: "*"
  eslint-plugin-prettier@*:
    dependencies:
      eslint: "*"
      prettier: "*"
  eslint-plugin-turbo@*:
    dependencies:
      eslint: "*"
  next@*:
    dependencies:
      react: "*"
      react-dom: "*"
  ts-jest@*:
    dependencies:
      jest: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-3.6.4.cjs
