immutablePatterns:
  - .pnp.*

initScope: next-mobx-store

nodeLinker: pnp

packageExtensions:
<<<<<<< HEAD
  "@testing-library/react@*":
    dependencies:
      react-dom: "*"
  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": "*"
=======
>>>>>>> 1cd44b4920266406c9e219c91ad6cd1295f5e1fc
  eslint-config-custom@*:
    dependencies:
      eslint: "*"
      eslint-plugin-turbo: "*"
      prettier: "*"
  eslint-plugin-prettier@*:
    dependencies:
      eslint: "*"
      prettier: "*"
  eslint-plugin-turbo@*:
    dependencies:
      eslint: "*"
  next@*:
    dependencies:
      react: "*"
      react-dom: "*"
  debug@*:
    dependencies:
      supports-color: "8.1.1"

pnpEnableEsmLoader: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.6.4.cjs
