name: Release

on:
  push:
    branches:
      - main
env:
  YARN_RC_FILENAME: '.yarnrc.nm.yml'
  YARN_LOCK_FILENAME: 'yarn.nm.lock'
  PRISMA_SKIP_POSTINSTALL_GENERATE: 'true'
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 'true'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        uses: ./.github/actions/yarn-nm-install

      - name: Creating .npmrc
        run: | 
          cat << EOF > "$HOME/.npmrc"
            email=opterk@gmail.com
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:          
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}      
      - name: Lint
        run: yarn lint

      - name: Build Packages
        run: yarn build
        
      - name: Test
        run: yarn test

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
